// split_pages.js
// Splits long Haggadah sections into multiple pages, keeping paragraphs together.
// Max 10 segments per page (~1.5 screens). Writes updated haggadah_data.js.

const fs = require('fs');
const H = require('./public/haggadah_data.js');

const MAX_SEGS = 10;

// Map of section titles that need splitting, with Hebrew letter suffixes
const heLetters = ['א', 'ב', 'ג', 'ד', 'ה', 'ו', 'ז', 'ח', 'ט', 'י', 'יא', 'יב'];

function splitSection(section) {
    if (section.segments.length <= MAX_SEGS) return [section];

    const pages = [];
    let currentSegs = [];

    for (let i = 0; i < section.segments.length; i++) {
        const seg = section.segments[i];
        const segText = seg.he || '';

        // A segment is a "paragraph break" if it ends with a period/colon/newline
        // or the next segment starts with a Hebrew instruction (small tag)
        const isNatualBreak = segText.includes('<small>') || segText.includes('<br') || segText.trim() === '';

        currentSegs.push(seg);

        // Check if we should break here
        const nextSeg = section.segments[i + 1];
        const nextIsInstruction = nextSeg && (
            (nextSeg.he || '').includes('<small>') ||
            (nextSeg.he || '').startsWith('\n')
        );

        if (currentSegs.length >= MAX_SEGS && (isNatualBreak || nextIsInstruction || i === section.segments.length - 1)) {
            pages.push(currentSegs);
            currentSegs = [];
        }
    }

    if (currentSegs.length > 0) {
        pages.push(currentSegs);
    }

    return pages.map((segs, idx) => ({
        title: pages.length === 1 ? section.title : `${section.title} (${heLetters[idx] || idx + 1})`,
        segments: segs,
        partOf: section.title,
        partIndex: idx,
        partTotal: pages.length
    }));
}

const result = [];
H.forEach(section => {
    const parts = splitSection(section);
    parts.forEach(p => result.push(p));
});

// Report
console.log('Pages after splitting:');
result.forEach((p, i) => console.log(`  ${i}: ${p.title} — ${p.segments.length} segs`));

// Find שולחן עורך index
const shulchanIdx = result.findIndex(p => p.title.includes('שֻׁלְחָן עוֹרֵךְ'));
console.log(`\n✅ שולחן עורך is page index: ${shulchanIdx}`);

const jsContent = `// AUTO-GENERATED by split_pages.js
// שולחן עורך is at page index: ${shulchanIdx}
const HAGGADAH = ${JSON.stringify(result, null, 2)};

const SHULCHAN_ORECH_PAGE = ${shulchanIdx};

if (typeof module !== 'undefined') module.exports = HAGGADAH;`;

fs.writeFileSync('./public/haggadah_data.js', jsContent);
console.log(`\nWrote ${result.length} pages to haggadah_data.js`);
