import type { HaggadahSection } from '../../../shared-types';

export const haggadahSections: HaggadahSection[] = [
    {
        id: 'kadesh',
        order: 1,
        title: 'Kadesh',
        titleHebrew: 'קַדֵּשׁ',
        hebrew: 'בָּרוּךְ אַתָּה יְיָ, אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, בּוֹרֵא פְּרִי הַגָּפֶן.',
        transliteration: 'Baruch Atah Adonai, Eloheinu Melech haolam, borei p\'ri hagafen.',
        english: 'Blessed are You, Eternal our God, Sovereign of the universe, who creates the fruit of the vine.',
        sceneIds: ['scene-kadesh-1'],
        hasVote: false,
    },
    {
        id: 'urchatz',
        order: 2,
        title: 'Urchatz',
        titleHebrew: 'וּרְחַץ',
        hebrew: 'נוֹטְלִים אֶת הַיָּדַיִם.',
        transliteration: 'Washing of the hands.',
        english: 'We wash our hands without saying a blessing — a moment of quiet preparation.',
        sceneIds: [],
    },
    {
        id: 'karpas',
        order: 3,
        title: 'Karpas',
        titleHebrew: 'כַּרְפַּס',
        hebrew: 'בָּרוּךְ אַתָּה יְיָ, אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, בּוֹרֵא פְּרִי הָאֲדָמָה.',
        transliteration: 'Baruch Atah Adonai, Eloheinu Melech haolam, borei p\'ri haadamah.',
        english: 'We dip a vegetable in salt water — the salt water represents the tears of our ancestors in Egypt.',
        sceneIds: ['scene-karpas-1'],
    },
    {
        id: 'yachatz',
        order: 4,
        title: 'Yachatz',
        titleHebrew: 'יַחַץ',
        hebrew: 'בּוֹצְעִים אֶת הַמַּצָּה הָאֶמְצָעִית לִשְׁנַיִם.',
        transliteration: 'The middle matzah is broken in two.',
        english: 'The middle matzah is broken. Half is set aside as the Afikomen — hidden for children to find.',
        sceneIds: ['scene-yachatz-1'],
    },
    {
        id: 'maggid-intro',
        order: 5,
        title: 'Maggid — The Story Begins',
        titleHebrew: 'מַגִּיד — הָא לַחְמָא',
        hebrew: 'הָא לַחְמָא עַנְיָא דִּי אֲכָלוּ אַבְהָתָנָא בְּאַרְעָא דְמִצְרָיִם. כָּל דִּכְפִין יֵיתֵי וְיֵיכוֹל.',
        transliteration: 'Ha lachma anya di achalu avhatana b\'ara d\'Mitzrayim. Kol dichfin yeitei v\'yeichol.',
        english: '"This is the bread of affliction, which our ancestors ate in Egypt. Let all who are hungry come and eat."',
        sceneIds: ['scene-halochem-1'],
    },
    {
        id: 'mah-nishtana',
        order: 6,
        title: 'Mah Nishtanah — The Four Questions',
        titleHebrew: 'מַה נִּשְׁתַּנָּה',
        hebrew: 'מַה נִּשְׁתַּנָּה הַלַּיְלָה הַזֶּה מִכָּל הַלֵּילוֹת?\nשֶׁבְּכָל הַלֵּילוֹת אָנוּ אוֹכְלִין חָמֵץ וּמַצָּה, הַלַּיְלָה הַזֶּה כֻּלּוֹ מַצָּה.\nשֶׁבְּכָל הַלֵּילוֹת אָנוּ אוֹכְלִין שְׁאָר יְרָקוֹת, הַלַּיְלָה הַזֶּה מָרוֹר.',
        transliteration: 'Mah nishtanah halailah hazeh mikol haleilot?',
        english: 'Why is this night different from all other nights?\nOn all other nights we eat bread or matzah, tonight only matzah.\nOn all other nights we eat all vegetables, tonight bitter herbs.',
        sceneIds: ['scene-mahnishtana-1'],
    },
    {
        id: 'avadim',
        order: 7,
        title: 'We Were Slaves',
        titleHebrew: 'עֲבָדִים הָיִינוּ',
        hebrew: 'עֲבָדִים הָיִינוּ לְפַרְעֹה בְּמִצְרָיִם, וַיּוֹצִיאֵנוּ יְיָ אֱלֹהֵינוּ מִשָּׁם בְּיָד חֲזָקָה וּבִזְרֹעַ נְטוּיָה.',
        transliteration: 'Avadim hayinu l\'Pharaoh b\'Mitzrayim, vayotzi\'einu Adonai Eloheinu misham b\'yad chazakah uvizro\'a netuyah.',
        english: 'We were slaves to Pharaoh in Egypt, and the Eternal our God brought us out of there with a mighty hand and an outstretched arm.',
        sceneIds: ['scene-slavery-1', 'scene-slavery-2'],
    },
    {
        id: 'four-sons',
        order: 8,
        title: 'The Four Sons',
        titleHebrew: 'אַרְבָּעָה בָנִים',
        hebrew: 'אֶחָד חָכָם, וְאֶחָד רָשָׁע, וְאֶחָד תָּם, וְאֶחָד שֶׁאֵינוֹ יוֹדֵעַ לִשְׁאוֹל.',
        transliteration: 'Echad chacham, v\'echad rasha, v\'echad tam, v\'echad she\'eino yodea lish\'ol.',
        english: 'One wise, one wicked, one simple, and one who does not know how to ask.',
        sceneIds: ['scene-foursons-1'],
        hasVote: true,
        voteQuestion: 'Who is the Wise Son tonight? 🦉',
        voteChoices: ['participant-1', 'participant-2', 'participant-3', 'participant-4'],
    },
    {
        id: 'ten-plagues',
        order: 9,
        title: 'The Ten Plagues',
        titleHebrew: 'עֶשֶׂר מַכּוֹת',
        hebrew: 'דָּם. צְפַרְדֵּעַ. כִּנִּים. עָרוֹב. דֶּבֶר. שְׁחִין. בָּרָד. אַרְבֶּה. חֹשֶׁךְ. מַכַּת בְּכוֹרוֹת.',
        transliteration: 'Dam. Tzfardea. Kinim. Arov. Dever. Sh\'chin. Barad. Arbeh. Choshech. Makat Bechorot.',
        english: 'Blood. Frogs. Lice. Wild Animals. Cattle Disease. Boils. Hail. Locusts. Darkness. Death of the Firstborn.',
        sceneIds: ['scene-plagues-1', 'scene-plagues-2'],
        hasScratch: true,
        scratchReveal: 'Scratch to reveal the next plague! 🐸',
    },
    {
        id: 'dayenu',
        order: 10,
        title: 'Dayenu',
        titleHebrew: 'דַּיֵּנוּ',
        hebrew: 'אִלּוּ הוֹצִיאָנוּ מִמִּצְרַיִם, דַּיֵּנוּ!\nאִלּוּ נָתַן לָנוּ אֶת הַשַּׁבָּת, דַּיֵּנוּ!\nאִלּוּ נָתַן לָנוּ אֶת הַתּוֹרָה, דַּיֵּנוּ!',
        transliteration: 'Ilu hotzi\'anu mi\'Mitzrayim, Dayenu!\nIlu natan lanu et haShabbat, Dayenu!\nIlu natan lanu et haTorah, Dayenu!',
        english: 'Had He only taken us out of Egypt — it would have been enough!\nHad He only given us the Sabbath — it would have been enough!\nHad He only given us the Torah — it would have been enough!',
        sceneIds: ['scene-dayenu-1'],
    },
    {
        id: 'pesach-matzah-maror',
        order: 11,
        title: 'Pesach, Matzah, Maror',
        titleHebrew: 'פֶּסַח מַצָּה וּמָרוֹר',
        hebrew: 'רַבָּן גַּמְלִיאֵל הָיָה אוֹמֵר: כָּל שֶׁלֹּא אָמַר שְׁלֹשָׁה דְּבָרִים אֵלּוּ בַּפֶּסַח, לֹא יָצָא יְדֵי חוֹבָתוֹ: פֶּסַח, מַצָּה, וּמָרוֹר.',
        transliteration: 'Rabban Gamliel would say: whoever has not said these three things at Passover has not fulfilled their obligation: Pesach, Matzah, and Maror.',
        english: 'The Passover Lamb recalls that God passed over our homes. Matzah recalls our hastened exit. The bitter herbs recall the bitterness of slavery.',
        sceneIds: ['scene-pmmm-1'],
    },
    {
        id: 'hallel-part1',
        order: 12,
        title: 'Hallel',
        titleHebrew: 'הַלֵּל',
        hebrew: 'הַלְלוּיָהּ, הַלְלוּ עַבְדֵי יְיָ, הַלְלוּ אֶת שֵׁם יְיָ.\nיְהִי שֵׁם יְיָ מְבֹרָךְ מֵעַתָּה וְעַד עוֹלָם.',
        transliteration: 'Halleluyah! Praise the servants of God, praise the name of God.\nBlessed be the name of God now and forever.',
        english: 'In praise of God who brings the lowly to greatness — who raises the poor from the dust.',
        sceneIds: ['scene-hallel-1'],
    },
    {
        id: 'shulchan-orech',
        order: 13,
        title: 'Shulchan Orech — The Meal',
        titleHebrew: 'שֻׁלְחָן עוֹרֵךְ',
        hebrew: 'אוֹכְלִים וְשׁוֹתִים לְשֹׂבַע.',
        transliteration: 'Shulchan Orech.',
        english: '🍽️ Now we eat! Enjoy the Seder meal together. Beshaat tov u\'mutzlach — may it be wonderful and delicious!',
        sceneIds: ['scene-meal-1'],
    },
    {
        id: 'tzafun',
        order: 14,
        title: 'Tzafun — The Afikomen',
        titleHebrew: 'צָפוּן',
        hebrew: 'מוֹצִיאִים אֶת הָאֲפִיקוֹמָן וְאוֹכְלִים אוֹתוֹ.',
        transliteration: 'The Afikomen is retrieved and eaten.',
        english: 'Children search for the hidden Afikomen! The child who finds it may negotiate with the host for a prize. 🔍',
        sceneIds: ['scene-tzafun-1'],
    },
    {
        id: 'barech',
        order: 15,
        title: 'Barech — Grace After Meals',
        titleHebrew: 'בָּרֵךְ',
        hebrew: 'בָּרוּךְ אַתָּה יְיָ, הַזָּן אֶת הַכֹּל.',
        transliteration: 'Baruch Atah Adonai, hazan et hakol.',
        english: 'We thank God for the food we have eaten and for the land. We pour a third cup of wine.',
        sceneIds: [],
    },
    {
        id: 'elijah',
        order: 16,
        title: 'Elijah\'s Cup',
        titleHebrew: 'כּוֹס אֵלִיָּהוּ',
        hebrew: 'פּוֹתְחִים אֶת הַדֶּלֶת לְאֵלִיָּהוּ הַנָּבִיא.',
        transliteration: 'We open the door for Elijah the Prophet.',
        english: 'The door is opened. We pour a cup of wine for Elijah, the prophet who will herald the messianic era. 🚪',
        sceneIds: ['scene-elijah-1'],
        hasVote: true,
        voteQuestion: 'Did the wine in Elijah\'s cup move? 👀',
        voteChoices: ['yes', 'no'],
    },
    {
        id: 'hallel-song',
        order: 17,
        title: 'Songs of Hallel',
        titleHebrew: 'שִׁיר הַהַלֵּל',
        hebrew: 'הוֹדוּ לַייָ כִּי טוֹב, כִּי לְעוֹלָם חַסְדּוֹ.\nיֹאמַר נָא יִשְׂרָאֵל, כִּי לְעוֹלָם חַסְדּוֹ.',
        transliteration: 'Hodu l\'Adonai ki tov, ki l\'olam chasdo. Yomar na Yisrael, ki l\'olam chasdo.',
        english: 'Give praise to God, for He is good — His love endures forever.',
        sceneIds: ['scene-redsea-1'],
    },
    {
        id: 'nirtzah',
        order: 18,
        title: 'Nirtzah — Acceptance',
        titleHebrew: 'נִרְצָה',
        hebrew: 'חֲסַל סִדּוּר פֶּסַח כְּהִלְכָתוֹ. לְשָׁנָה הַבָּאָה בִּירוּשָׁלָיִם!',
        transliteration: 'Chasal siddur Pesach k\'hilchato. L\'shanah haba\'ah b\'Yerushalayim!',
        english: 'The Passover Seder is now complete. Next year in Jerusalem! 🕊️',
        sceneIds: ['scene-nirtzah-1'],
        hasVote: true,
        voteQuestion: 'Who was the best Seder guest tonight? 🏆',
        voteChoices: ['participant-1', 'participant-2', 'participant-3'],
    },
    {
        id: 'chad-gadya',
        order: 19,
        title: 'Chad Gadya',
        titleHebrew: 'חַד גַּדְיָא',
        hebrew: 'חַד גַּדְיָא, חַד גַּדְיָא.\nדְּזַבִּין אַבָּא בִּתְרֵי זוּזֵי, חַד גַּדְיָא, חַד גַּדְיָא.',
        transliteration: 'Chad gadya, chad gadya. D\'zabin abba bitrei zuzei, chad gadya, chad gadya.',
        english: 'One little goat, one little goat, that my father bought for two coins — a chaotic, joyful allegory of history! 🐐',
        sceneIds: ['scene-chadgadya-1'],
    },
];
